"""
Hardcoded supplier → category mapping.
Categories: Mecânico | Elétrico | Pneumático
Best-effort initial categorization — use the Excel dropdown to correct any entry.
"""

CATEGORIAS = {
    "AIM SOLDER": "Elétrico",
    "AND": "Elétrico",
    "ABB": "Elétrico",
    "Accuride": "Mecânico",
    "Advantech": "Elétrico",
    "Afag": "Pneumático",
    "Allen-Bradley": "Elétrico",
    "Amada": "Mecânico",
    "Ammeraal beltech": "Mecânico",
    "Amplicon": "Elétrico",
    "Antistat": "Elétrico",
    "Apex": "Mecânico",
    "Aquaeden": "Mecânico",
    "Asahi Yukizai": "Pneumático",
    "ASS": "Elétrico",
    "ASUS": "Elétrico",
    "Asutec": "Mecânico",
    "Ateq": "Pneumático",
    "Atlas Copco": "Pneumático",
    "Aventics": "Pneumático",
    "Balluf": "Elétrico",
    "Banner": "Elétrico",
    "Barboflex": "Mecânico",
    "Baumer": "Elétrico",
    "Becker": "Pneumático",
    "Beckhoff": "Elétrico",
    "Beijer Electronics": "Elétrico",
    "Bene inox": "Mecânico",
    "Berger Lahr": "Elétrico",
    "Blickle": "Mecânico",
    "Bru y Rubio": "Mecânico",
    "Bosch Automation": "Elétrico",
    "Bosch Rexroth": "Mecânico",
    "Boteco": "Mecânico",
    "Burkert": "Pneumático",
    "Burster": "Elétrico",
    "CAB": "Elétrico",
    "Captron": "Elétrico",
    "Camozzi": "Pneumático",
    "Casalmáquinas": "Mecânico",
    "Cembre": "Elétrico",
    "Cherry": "Elétrico",
    "Chiaravalli": "Mecânico",
    "Cognex": "Elétrico",
    "Contrinex": "Elétrico",
    "Coolens": "Mecânico",
    "Datalogic": "Elétrico",
    "DCM Sistemes": "Elétrico",
    "Dell": "Elétrico",
    "Deprag": "Pneumático",
    "Desoutter": "Elétrico",
    "De-Sta-Co": "Mecânico",
    "Deimos": "Mecânico",
    "Denso": "Elétrico",
    "Di-Soric": "Elétrico",
    "Dini Argeo": "Elétrico",
    "Dirak": "Mecânico",
    "Doceram": "Mecânico",
    "Dopag": "Mecânico",
    "DPV": "Mecânico",
    "Dukane": "Elétrico",
    "Dunkermotoren": "Elétrico",
    "Eaton": "Elétrico",
    "Efectoled": "Elétrico",
    "Egana": "Mecânico",
    "Eldon": "Elétrico",
    "Electron": "Elétrico",
    "Elesa": "Mecânico",
    "Elesa+Ganter": "Mecânico",
    "Elcom": "Elétrico",
    "Elfin": "Elétrico",
    "Emile Maurin": "Mecânico",
    "Enidine": "Mecânico",
    "Epson": "Elétrico",
    "Ersa": "Elétrico",
    "Ettinger": "Mecânico",
    "Equinotec": "Mecânico",
    "ETL": "Elétrico",
    "Everett C.T.": "Elétrico",
    "Euchner": "Elétrico",
    "Fabory": "Mecânico",
    "Fag": "Mecânico",
    "Fanamol": "Mecânico",
    "Fandis": "Elétrico",
    "Fanuc": "Elétrico",
    "Farnell": "Elétrico",
    "Fasten": "Mecânico",
    "Fath": "Mecânico",
    "Faytech": "Elétrico",
    "Fersilva": "Mecânico",
    "Festo": "Pneumático",
    "Fett": "Mecânico",
    "Fibro": "Mecânico",
    "Fitek": "Mecânico",
    "Fixo": "Mecânico",
    "Fixsolda": "Elétrico",
    "Fli": "Mecânico",
    "Footmaster": "Mecânico",
    "Fortest": "Elétrico",
    "Frezite": "Mecânico",
    "FKK": "Mecânico",
    "Gayner": "Mecânico",
    "Gemalto": "Elétrico",
    "Greenkinetics": "Elétrico",
    "Greenlux": "Elétrico",
    "Gewiss": "Elétrico",
    "Goldl cke": "Mecânico",
    "GomsiParts": "Mecânico",
    "Good-Hand": "Mecânico",
    "Gutekunst": "Mecânico",
    "Gimatic": "Pneumático",
    "Habasit": "Mecânico",
    "Hager": "Elétrico",
    "Hansen": "Mecânico",
    "Harting": "Elétrico",
    "Hasco": "Mecânico",
    "Heidenhain": "Elétrico",
    "Heitec": "Elétrico",
    "Hiwin": "Mecânico",
    "Hoffman": "Elétrico",
    "HP": "Elétrico",
    "Huco": "Mecânico",
    "Huf": "Mecânico",
    "Hypertronics": "Elétrico",
    "IAI": "Elétrico",
    "IBC": "Mecânico",
    "IDE": "Elétrico",
    "IDS": "Elétrico",
    "IFM": "Elétrico",
    "Igus": "Mecânico",
    "IHS Handling": "Mecânico",
    "IKO": "Mecânico",
    "INA": "Mecânico",
    "Infaimon": "Elétrico",
    "Ingun": "Elétrico",
    "Itec": "Mecânico",
    "Item": "Mecânico",
    "Itt": "Elétrico",
    "Jacob": "Elétrico",
    "Jaguar": "Mecânico",
    "Juncor": "Mecânico",
    "Jura-Schrauben": "Mecânico",
    "JVL": "Elétrico",
    "Keyence": "Elétrico",
    "Kistler": "Elétrico",
    "Kipp": "Mecânico",
    "Kolver": "Elétrico",
    "Kuka": "Elétrico",
    "Lanema": "Mecânico",
    "Lapp Kabel": "Elétrico",
    "Lauda": "Elétrico",
    "Legrand": "Elétrico",
    "Legris": "Pneumático",
    "Lenovo": "Elétrico",
    "Lenze": "Elétrico",
    "Leschhorn": "Mecânico",
    "LMI Technologies": "Elétrico",
    "Logitech": "Elétrico",
    "Lumberg": "Elétrico",
    "Lupatec": "Mecânico",
    "Luxtar": "Elétrico",
    "Lypsis": "Mecânico",
    "L2W": "Mecânico",
    "Manutan": "Mecânico",
    "Marbett": "Mecânico",
    "Marchesini": "Mecânico",
    "MayTeC": "Mecânico",
    "Macsa": "Elétrico",
    "Mauser": "Mecânico",
    "Meanwell": "Elétrico",
    "Mecanarte": "Mecânico",
    "Megatron Elecktronik": "Elétrico",
    "Menekes": "Elétrico",
    "Merlin Gerin": "Elétrico",
    "Metal Work": "Pneumático",
    "Meusburger": "Mecânico",
    "Misumi": "Mecânico",
    "Mitutoyo": "Elétrico",
    "Moeller": "Elétrico",
    "Montech": "Mecânico",
    "Murreletronik": "Elétrico",
    "Mustek": "Elétrico",
    "Neugart": "Mecânico",
    "Nex Flow": "Pneumático",
    "NB": "Mecânico",
    "NBK": "Mecânico",
    "Nicolau Rosa": "Mecânico",
    "Nord": "Mecânico",
    "Norelem": "Mecânico",
    "NSK": "Mecânico",
    "NTN": "Mecânico",
    "Obo Bettermann": "Elétrico",
    "OleoDinamica Marchesini": "Mecânico",
    "OMC": "Mecânico",
    "Omega": "Elétrico",
    "Omron": "Elétrico",
    "Omge": "Mecânico",
    "Optibelt": "Mecânico",
    "Opto Engineering": "Elétrico",
    "Oriental Motor": "Elétrico",
    "Panasonic": "Elétrico",
    "Panduit": "Elétrico",
    "Patlite": "Elétrico",
    "Paulifer": "Mecânico",
    "PCE": "Elétrico",
    "Pemsa": "Elétrico",
    "Pepperl+Fuchs": "Elétrico",
    "Pfeiffer": "Pneumático",
    "Phasa": "Elétrico",
    "Philips": "Elétrico",
    "Phoenix Contact": "Elétrico",
    "Pilz": "Elétrico",
    "Pinet": "Mecânico",
    "PMA": "Elétrico",
    "PMI": "Mecânico",
    "Potermic": "Elétrico",
    "Proface": "Elétrico",
    "Promag": "Elétrico",
    "Promess": "Elétrico",
    "Purex": "Elétrico",
    "Puzzle Advance": "Mecânico",
    "Rabourdin": "Mecânico",
    "Rad": "Elétrico",
    "Reichelt": "Elétrico",
    "Reiman": "Mecânico",
    "Richco": "Mecânico",
    "Rittal": "Elétrico",
    "Rockwell": "Elétrico",
    "Rodalg s": "Mecânico",
    "Rohde & Schwarz": "Elétrico",
    "Rolisa": "Mecânico",
    "Rollon": "Mecânico",
    "Rose": "Elétrico",
    "Rose Krieger": "Mecânico",
    "Rotex": "Mecânico",
    "RS": "Elétrico",
    "Ruwac": "Pneumático",
    "RW": "Mecânico",
    "Sato": "Elétrico",
    "Satech": "Mecânico",
    "Schaeffner": "Elétrico",
    "Schmersal": "Elétrico",
    "Schmidt": "Mecânico",
    "Schneider": "Elétrico",
    "Schunk": "Mecânico",
    "Schrader": "Pneumático",
    "Schroff": "Elétrico",
    "SEW": "Elétrico",
    "Sejin": "Elétrico",
    "Selfoil": "Mecânico",
    "Sensopart": "Elétrico",
    "Senstronic": "Elétrico",
    "Shunk": "Mecânico",
    "Sick": "Elétrico",
    "Siemens": "Elétrico",
    "SKF": "Mecânico",
    "SMAC": "Elétrico",
    "SMC": "Pneumático",
    "SNR": "Mecânico",
    "Special springs": "Mecânico",
    "Socafluid": "Pneumático",
    "Sofima": "Pneumático",
    "Solartron": "Elétrico",
    "Sonitek": "Elétrico",
    "Sonorous": "Elétrico",
    "Sove": "Mecânico",
    "Staubli": "Mecânico",
    "Stieber": "Mecânico",
    "Supermagnete": "Mecânico",
    "Sutafer": "Mecânico",
    "Switchcraft": "Elétrico",
    "Swagelok": "Pneumático",
    "Syskomp": "Elétrico",
    "Tecnitem": "Mecânico",
    "Teknokol": "Mecânico",
    "Tente": "Mecânico",
    "Thenar": "Mecânico",
    "THK": "Mecânico",
    "Tironi": "Mecânico",
    "Triplo W": "Mecânico",
    "Troax": "Mecânico",
    "Trumpf": "Elétrico",
    "Turck": "Elétrico",
    "Vanel": "Mecânico",
    "Vetter": "Mecânico",
    "Vibrant": "Mecânico",
    "Vico": "Mecânico",
    "Videojet": "Elétrico",
    "Viewsonic": "Elétrico",
    "Xecro": "Elétrico",
    "Wago": "Elétrico",
    "Waicon": "Elétrico",
    "Walter-Praezision": "Mecânico",
    "Wandres": "Mecânico",
    "Weber": "Mecânico",
    "Wemo": "Elétrico",
    "Weidmuller": "Elétrico",
    "Weintek": "Elétrico",
    "Weiss": "Mecânico",
    "Weller": "Elétrico",
    "Wenglor": "Elétrico",
    "Werma": "Elétrico",
    "Wide Range": "Elétrico",
    "Wittenstein Alpha": "Mecânico",
    "Wiva": "Elétrico",
    "Wolfgang Warmbier": "Elétrico",
    "Woerner": "Mecânico",
    "Yaskawa": "Elétrico",
    "Zebra": "Elétrico",
    "Zimmer": "Mecânico",
    "Zitec": "Mecânico",
}

VALID_CATEGORIES = ("Mecânico", "Elétrico", "Pneumático")
DEFAULT_CATEGORY = "Mecânico"
